---
title           : "Reproducibility mini project: Alberta trees"
shorttitle      : "My preregistration"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Rolando Trejo P.
    affiliation : "1"
  - name        : 
    affiliation : 

affiliation:
  - id          : 1
    institution : Institut de recherche en biologie végétale, Université de Montréal
  - id          : 
    institution : 

output: prereg::prereg_pdf
---

## Data collection

<!-- Have any data been collected for this study already? (Note: "Yes" is not an accepted answer.) -->

**Yes**, this mini reproducibility project was built using rescued data by Amelia Hesketh, Jenna Loesberg, Ellen Bledsoe, Justine Karst,and Ellen Macdonald in 2021 from an Alberta legacy dataset spanning four decades (1980-2015). 

## Hypothesis

<!-- What's the main question being asked or hypothesis being tested in this study? -->

> A very simple model is explored in this reproducibility project: Does species richness varies along the soil temperature?

## Dependent variable

<!-- Describe the key dependent variable(s) specifying how they will be measured. -->

> To answer the main question following a reproducible workflow, I use two variables. Vascular species richness and soil temperature en Celsius.

## Conditions

<!-- How many and which conditions will participants be assigned to? -->

> These data cames from a long-term survay analyzing changes in seasonal dynamics and succession within boreal forest communities. It serves as a baseline for comparison with future forest conditions in unmanaged, managed, and reclaimed forests.


## Analyses

<!-- Specify exactly which analyses you will conduct to examine the main question/hypothesis. -->

> I use reproducibility workflow in ecology and evolution. I used open access data, which is available in Boreales (see references below). This data was rescued by Hesketh et al., 2021. This mini project was created with the open-source software R, OSF and GitHub. Linear regression and a comparison with non-linear regression were used as part of the analyses.

## Outliers and exclusions

<!-- Describe exactly how outliers will be defined and handled, and your precise rule(s) for excluding observations. -->

> The data used in this mini project does not considere discarding outliers.

## Sample size

<!-- How many observations will be collected or what will determine sample size? No need to justify decision, but be precise about _exactly_ how the number will be determined. -->

> I use two different datasets: 1) Hondo Vascular Cover (1980-2015) and 2) Hondo Soil Temperature (1980-2010). Each dataset presents 11289 observations.

## Other

<!-- Anything else you would like to pre-register? (e.g., secondary analyses, variables collected for exploratory purposes, unusual analyses planned?) -->

> All code used in this project is available on GitHub https://github.com/CIEE-Living-Data-Project/Rolando_Trejo_Reproducibility_LDP_2022.

## Study type

-   Class project or assignment: Productibity and Reproducibility in Ecology and Evolution.


# References

Hesketh, A., Loesberg, J., Bledsoe, E., Karst, J., & Macdonald, E. (2021). Seasonal and annual dynamics of western Canadian boreal forest plant communities: A legacy dataset spanning four decades [Data set]. Scholars Portal Dataverse. https://doi.org/10.5683/SP3/PZCAVE

## 

```{=tex}
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
```
\noindent
